/**
 *
 * $Id$
 */
package org.mcmaster.workflowplus.wfp.validation;

import org.eclipse.emf.common.util.EList;

import org.mcmaster.workflowplus.wfp.Argument;
import org.mcmaster.workflowplus.wfp.Constraint;

/**
 * A sample validator interface for {@link org.mcmaster.workflowplus.wfp.Argument}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArgumentValidator {
	boolean validate();

	boolean validateDescription(boolean value);

	boolean validateSyntactic(boolean value);

	boolean validateConstraint(EList<Constraint> value);

	boolean validateConstructedBy(EList<Argument> value);

	boolean validateConstructs(EList<Argument> value);
}
