/**
 *
 * $Id$
 */
package org.mcmaster.workflowplus.wfp.validation;

import org.mcmaster.workflowplus.wfp.Node;

/**
 * A sample validator interface for {@link org.mcmaster.workflowplus.wfp.Association}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssociationValidator {
	boolean validate();

	boolean validateSrc(Node value);

	boolean validateTgt(Node value);

	boolean validateMultAtSrc(String value);

	boolean validateMultAtTgt(String value);

	boolean validateLabelAtSrc(String value);

	boolean validateLabelAtTgt(String value);
}
