/**
 *
 * $Id$
 */
package org.mcmaster.workflowplus.wfp.validation;

import org.mcmaster.workflowplus.wfp.Data;

/**
 * A sample validator interface for {@link org.mcmaster.workflowplus.wfp.Input}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputValidator {
	boolean validate();

	boolean validateSrc(Data value);

	boolean validateTgt(org.mcmaster.workflowplus.wfp.Process value);

	boolean validateMultAtSrc(String value);

	boolean validateMultAtTgt(String value);
}
