/**
 *
 * $Id$
 */
package wFP_V2.validation;

import org.eclipse.emf.common.util.EList;

import wFP_V2.Argument;
import wFP_V2.Constraint;

/**
 * A sample validator interface for {@link wFP_V2.Argument}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArgumentValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateDescription(String value);

	boolean validateConstraint(EList<Constraint> value);

	boolean validateConstructs(EList<Argument> value);

	boolean validateConstructedBy(EList<Argument> value);

	boolean validateSyntactic(boolean value);
}
