/**
 *
 * $Id$
 */
package wFP_V2.validation;

import org.eclipse.emf.common.util.EList;
import wFP_V2.Node;

/**
 * A sample validator interface for {@link wFP_V2.Composition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CompositionValidator {
	boolean validate();

	boolean validateComposes(Node value);

	boolean validateComposedOf(Node value);

	boolean validateMultAtTgt(String value);

	boolean validateLabelAtTgt(String value);

	boolean validateSrc(EList<Node> value);

	boolean validateSrc(Node value);

	boolean validateTgt(EList<Node> value);

	boolean validateTgt(Node value);
}
