/**
 *
 * $Id$
 */
package wFP_V2.validation;

import org.eclipse.emf.common.util.EList;

import wFP_V2.Argument;
import wFP_V2.Node;
import wFP_V2.Reference;

/**
 * A sample validator interface for {@link wFP_V2.Constraint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateNode(EList<Node> value);

	boolean validateBody(String value);

	boolean validateOCL(String value);

	boolean validateType(String value);

	boolean validateDescription(String value);

	boolean validateSyntactic(boolean value);

	boolean validateArgument(EList<Argument> value);

	boolean validateReference(EList<Reference> value);

	boolean validateReference(Reference value);
}
