/**
 *
 * $Id$
 */
package wFP_V2.validation;

import org.eclipse.emf.common.util.EList;

import wFP_V2.Data;

/**
 * A sample validator interface for {@link wFP_V2.Data_Definition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Data_DefinitionValidator {
	boolean validate();

	boolean validateData(EList<Data> value);

	boolean validateIsNormative(boolean value);
}
