/**
 *
 * $Id$
 */
package wFP_V2.validation;

import wFP_V2.Data;

/**
 * A sample validator interface for {@link wFP_V2.Output}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OutputValidator {
	boolean validate();

	boolean validateSrc_process(wFP_V2.Process value);

	boolean validateTgt_data(Data value);

	boolean validateMultAtSrc(String value);

	boolean validateMultAtTgt(String value);

	boolean validateTgt(Data value);

	boolean validateSrc(wFP_V2.Process value);
}
