/**
 *
 * $Id$
 */
package wFP_V2.validation;

import wFP_V2.Reify_Association;

/**
 * A sample validator interface for {@link wFP_V2.Reference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReferenceValidator {
	boolean validate();

	boolean validateReify_association(Reify_Association value);

}
