/**
 *
 * $Id$
 */
package org.mcmaster.workflowplus.wfp.validation;

import org.eclipse.emf.common.util.EList;

import org.mcmaster.workflowplus.wfp.Argument;
import org.mcmaster.workflowplus.wfp.Node;
import org.mcmaster.workflowplus.wfp.Reference;

/**
 * A sample validator interface for {@link org.mcmaster.workflowplus.wfp.Constraint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintValidator {
	boolean validate();

	boolean validateBody(String value);

	boolean validateSyntactic(boolean value);

	boolean validateArgument(EList<Argument> value);

	boolean validateReference(EList<Reference> value);

	boolean validateNode(EList<Node> value);

	boolean validateName(String value);
}
