/**
 *
 * $Id$
 */
package org.mcmaster.workflowplus.wfp.validation;

import org.eclipse.emf.common.util.EList;

import org.mcmaster.workflowplus.wfp.Input;
import org.mcmaster.workflowplus.wfp.Output;

/**
 * A sample validator interface for {@link org.mcmaster.workflowplus.wfp.Data}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataValidator {
	boolean validate();

	boolean validateInput(EList<Input> value);

	boolean validateOutput(EList<Output> value);

	boolean validateName(String value);
}
