/**
 *
 * $Id$
 */
package org.mcmaster.workflowplus.wfp.validation;

import org.mcmaster.workflowplus.wfp.Node;
import org.mcmaster.workflowplus.wfp.Reference;

/**
 * A sample validator interface for {@link org.mcmaster.workflowplus.wfp.ReifyAssociation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReifyAssociationValidator {
	boolean validate();

	boolean validateTgt(Node value);

	boolean validateSrc(Reference value);

	boolean validateMultAtTgt(String value);

	boolean validateLabelAtTgt(String value);
}
